<?php

class Belanur_Facebook_Model_Adminhtml_System_Source_Language
{
    public function toOptionArray()
    {
        return array(
            array('value' => 'af_ZA', 'label' => 'Afrikaans - South Africa'),
			array('value' => 'sq_AL', 'label' => 'Albanian - Albania'),
			array('value' => 'hy_AM', 'label' => 'Armenian - Armenia'),
			array('value' => 'ay_BO', 'label' => 'Aymara - Bolivia'),
            array('value' => 'az_AZ', 'label' => 'Azerbaijani - Azerbaijan'),
			array('value' => 'eu_ES', 'label' => 'Basque - Spain'),
            array('value' => 'be_BY', 'label' => 'Belarusian - Belarus'),
			array('value' => 'bn_IN', 'label' => 'Bengali - India'),
			array('value' => 'bs_BA', 'label' => 'Bosnian - Bosnia and Herzegovina'),
            array('value' => 'bg_BG', 'label' => 'Bulgarian - Bulgaria'),
            array('value' => 'ca_ES', 'label' => 'Catalan - Spain'),
			array('value' => 'zh_CN', 'label' => 'Chinese - China'),
            array('value' => 'zh_HK', 'label' => 'Chinese - Hong Kong SAR China'),
            array('value' => 'zh_TW', 'label' => 'Chinese - Taiwan'),
			array('value' => 'hr_HR', 'label' => 'Croatian - Croatia'),
            array('value' => 'cs_CZ', 'label' => 'Czech - Czech Republic'),
            array('value' => 'da_DK', 'label' => 'Danish - Denmark'),
			array('value' => 'nl_BE', 'label' => 'Dutch - Belgium'),
            array('value' => 'nl_NL', 'label' => 'Dutch - Netherlands'),
			array('value' => 'en_IN', 'label' => 'English - India'),
            array('value' => 'en_GB', 'label' => 'English - United Kingdom'),
            array('value' => 'en_US', 'label' => 'English - United States'),
			array('value' => 'et_EE', 'label' => 'Estonian - Estonia'),
			array('value' => 'fo_FO', 'label' => 'Faroese - Faroe Islands'),
			array('value' => 'fi_FI', 'label' => 'Finnish - Finland'),
            array('value' => 'fr_CA', 'label' => 'French - Canada'),
            array('value' => 'fr_FR', 'label' => 'French - France'),
			array('value' => 'gl_ES', 'label' => 'Galician - Spain'),
			array('value' => 'ka_GE', 'label' => 'Georgian - Georgia'),
            array('value' => 'de_DE', 'label' => 'German - Germany'),
            array('value' => 'el_GR', 'label' => 'Greek - Greece'),
            array('value' => 'gn_PY', 'label' => 'Guarani - Paraguay'),
            array('value' => 'gu_IN', 'label' => 'Gujarati - India'),
			array('value' => 'he_IL', 'label' => 'Hebrew - Israel'),
            array('value' => 'hi_IN', 'label' => 'Hindi - India'),
			array('value' => 'hu_HU', 'label' => 'Hungarian - Hungary'),
			array('value' => 'is_IS', 'label' => 'Icelandic - Iceland'),
			array('value' => 'id_ID', 'label' => 'Indonesian - Indonesia'),
			array('value' => 'ga_IE', 'label' => 'Irish - Ireland'),
            array('value' => 'it_IT', 'label' => 'Italian - Italy'),
			array('value' => 'ja_JP', 'label' => 'Japanese - Japan'),
            array('value' => 'jv_ID', 'label' => 'Javanese - Indonesia'),
			array('value' => 'kn_IN', 'label' => 'Kannada - India'),
			array('value' => 'kk_KZ', 'label' => 'Kazakh - Kazakhstan'),
            array('value' => 'km_KH', 'label' => 'Khmer - Cambodia'),
            array('value' => 'ko_KR', 'label' => 'Korean - Korea'),
            array('value' => 'ku_TR', 'label' => 'Kurdish - Turkey'),
			array('value' => 'la_VA', 'label' => 'Latin - Vatican'),
			array('value' => 'lv_LV', 'label' => 'Latvian - Latvia'),
            array('value' => 'lt_LT', 'label' => 'Lithuanian - Lithuania'),
			array('value' => 'mk_MK', 'label' => 'Macedonian - Macedonia'),
			array('value' => 'mg_MG', 'label' => 'Malagasy - Madagascar'),
			array('value' => 'ms_MY', 'label' => 'Malay - Malaysia'),
            array('value' => 'ml_IN', 'label' => 'Malayalam - India'),
            array('value' => 'mt_MT', 'label' => 'Maltese - Malta'),
			array('value' => 'mr_IN', 'label' => 'Marathi - India'),
            array('value' => 'mn_MN', 'label' => 'Mongolian - Mongolia'),
			array('value' => 'ne_NP', 'label' => 'Nepali - Nepal'),
			array('value' => 'se_NO', 'label' => 'Northern Sami - Norway'),
            array('value' => 'nb_NO', 'label' => 'Norwegian Bokmal - Norway'),
			array('value' => 'nn_NO', 'label' => 'Norwegian Nynorsk - Norway'),
			array('value' => 'ps_AF', 'label' => 'Pashto - Afghanistan'),
			array('value' => 'fa_IR', 'label' => 'Persian - Iran'),
			array('value' => 'pl_PL', 'label' => 'Polish - Poland'),
            array('value' => 'pt_BR', 'label' => 'Portuguese - Brazil'),
            array('value' => 'pt_PT', 'label' => 'Portuguese - Portugal'),
			array('value' => 'pa_IN', 'label' => 'Punjabi - India'),
			array('value' => 'qu_PE', 'label' => 'Quechua - Peru'),
            array('value' => 'rm_CH', 'label' => 'Rhaeto-Romance - Switzerland'),
            array('value' => 'ro_RO', 'label' => 'Romanian - Romania'),
            array('value' => 'ru_RU', 'label' => 'Russian - Russia'),
            array('value' => 'es_CL', 'label' => 'Spanish - Chile'),
            array('value' => 'es_CO', 'label' => 'Spanish - Colombia'),
			array('value' => 'es_MX', 'label' => 'Spanish - Mexico'),
            array('value' => 'es_ES', 'label' => 'Spanish - Spain'),
            array('value' => 'es_VE', 'label' => 'Spanish - Venezuela'),
            array('value' => 'sa_IN', 'label' => 'Sanskrit - India'),
            array('value' => 'sr_RS', 'label' => 'Serbian - Serbia'),
			array('value' => 'sk_SK', 'label' => 'Slovak - Slovakia'),
            array('value' => 'sl_SI', 'label' => 'Slovenian - Slovenia'),
            array('value' => 'so_SO', 'label' => 'Somali - Somalia'),
            array('value' => 'sv_SE', 'label' => 'Swedish - Sweden'),
            array('value' => 'sw_KE', 'label' => 'Swahili - Kenya'),
			array('value' => 'tl_PH', 'label' => 'Tagalog - Philippines'),
			array('value' => 'tg_TJ', 'label' => 'Tajik - Tajikistan'),
            array('value' => 'ta_IN', 'label' => 'Tamil - India'),
			array('value' => 'tt_RU', 'label' => 'Tatar - Russia'),
            array('value' => 'te_IN', 'label' => 'Telugu - India'),
            array('value' => 'th_TH', 'label' => 'Thai - Thailand'),
            array('value' => 'tr_TR', 'label' => 'Turkish - Turkey'),
            array('value' => 'uk_UA', 'label' => 'Ukrainian - Ukraine'),
            array('value' => 'ur_PK', 'label' => 'Urdu - Pakistan'),
            array('value' => 'uz_UZ', 'label' => 'Uzbek - Uzbekistan'),
            array('value' => 'vi_VN', 'label' => 'Vietnamese - Vietnam'),
			array('value' => 'cy_GB', 'label' => 'Welsh - United Kingdom'),
            array('value' => 'xh_ZA', 'label' => 'Xhosa - South Africa'),
            array('value' => 'zu_ZA', 'label' => 'Zulu - South Africa'),
        );
    }
}
